/**
 * DTP API
 * DTP API (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DtpCoreModelTimestamp {
    blockchain?: string;

    algorithm?: string;

    service?: string;

    source?: string;

    path?: string;

    registered?: number;

}
