/**
 * DTP API
 * DTP API (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DtpCoreModelClaim {
    root?: string;

    created?: number;

    issuer?: models.DtpCoreModelIssuerIdentity;

    subject?: models.DtpCoreModelSubjectIdentity;

    type?: string;

    value?: string;

    scope?: string;

    activate?: number;

    expire?: number;

    metadata?: string;

    timestamps?: Array<models.DtpCoreModelTimestamp>;

    templateId?: number;

}
