/**
 * DTP API
 * DTP API (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DtpGraphCoreModelQueryRequest {
    issuer?: models.DtpCoreModelIdentity;

    subjects?: Array<string>;

    types?: Array<string>;

    scope?: string;

    level?: number;

    flags?: DtpGraphCoreModelQueryRequest.FlagsEnum;

}
export namespace DtpGraphCoreModelQueryRequest {
    export enum FlagsEnum {
        LeafsOnly = <any> 'LeafsOnly',
        FullTree = <any> 'FullTree',
        NONE1 = <any> 'NONE1',
        IncludeClaimTrust = <any> 'IncludeClaimTrust',
        ServerSign = <any> 'ServerSign',
        IncludeTimestamp = <any> 'IncludeTimestamp',
        NONE2 = <any> 'NONE2'
    }
}
