/**
 * DTP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Claim {
    //id?: string;
    //root?: string;
    type?: string;

    algorithm?: string;

    created?: number;

    issuer?: models.IssuerIdentity;

    subject?: models.SubjectIdentity;

    value?: string;

    scope?: string;

    activate?: number;

    expire?: number;

    note?: string;

    templateId?: number;

    timestamps?: Array<models.Timestamp>;

}
