/**
 * DTP API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface QueryRequest {
    issuers?: string;

    subjects?: Array<models.SubjectQuery>;

    types?: Array<string>;

    scope?: models.TrustScope;

    level?: number;

    flags?: QueryRequest.FlagsEnum;

}
export namespace QueryRequest {
    export enum FlagsEnum {
        LeafsOnly = <any> 'LeafsOnly',
        FullTree = <any> 'FullTree',
        NONE1 = <any> 'NONE1',
        IncludeClaimTrust = <any> 'IncludeClaimTrust',
        ServerSign = <any> 'ServerSign',
        IncludeTimestamp = <any> 'IncludeTimestamp',
        NONE2 = <any> 'NONE2'
    }
}
